### ISSUE TITLE
too fast

### ISSUE THREAD

**Issue by jaikishantulswani** [0xbharath/slurp-old#1]
Hello @0xbharath 
Whenever I run slurp it is showing `too fast` error, can you please let me know whats going wrong ?

**Comment by akshanshshrivastava** [comment]
```
else if resp.StatusCode == 503 {
				log.Info("too fast")
                                 . . . 
```

if the service is unavailable it will show too fast

**Comment by unl1k3ly** [comment]
im getting the same...

**Comment by 0xbharath** [comment]
That's due to AWS rate limiting number of requests you can make as an unauthenticated user. Will look into handling this case better.

**Comment by unl1k3ly** [comment]
oh, i see... perhaps, we can force the request being authenticated form ~/.aws/credentials ?

**Comment by unl1k3ly** [comment]
Hi mate, wondering if we can use a DNS method  like https://github.com/koenrh/s3enum does to fix this 503 restriction ?
I'm really bad at go :( im sorry

**Comment by 0xbharath** [comment]
A new version of Slurp has been released (apparently by the original dev of Slurp). It supports credential scan and other features.

https://github.com/hehnope/slurp

Closing this task for now.
