### ISSUE TITLE
Not stable

### ISSUE THREAD

**Issue by Droidzzzio** [0xbharath/slurp-old#4]
Hello , 
this is a awesome tool but it is not stable , for running once or twice or couple of time it gives results as expected , but after that it stops giving results. I dont know what happens behind the scenes , but it just runs , then closes without giving results.

Regards

**Comment by 0xbharath** [comment]
That's because of AWS S3 rate limiting unauthenticated API calls, I suppose.

**Comment by 0xbharath** [comment]
I'll be working on updating Slurp to handle this problem.

**Comment by Droidzzzio** [comment]
Thank you for your response , and for now I figured out a way ....I am
changing location through vpn desktop application to different countries in
order to run the tool.
